name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "=== Debug info ==="
          whoami
          pwd
          
          echo "=== Set CORS_ORIGINS environment variable ==="
          export CORS_ORIGINS="https://eezyget.com"
          
          echo "=== Update PM2 environment ==="
          pm2 delete all || true
          pm2 start ecosystem.config.js || pm2 start --name eezyget-backend "npm start"
          
          echo "=== PM2 status ==="
          pm2 status
          
          echo "=== PM2 logs ==="
          pm2 logs --lines 3