name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "=== Simple debug test ==="
          whoami
          pwd
          
          echo "=== Check git status ==="
          find / -name ".git" -type d 2>/dev/null | head -3
          
          echo "=== PM2 restart without git pull ==="
          pm2 restart all
          
          echo "=== PM2 status ==="
          pm2 status
          
          echo "=== Success - Basic deployment done ==="