name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "=== Find working directory ==="
          APP_DIR=$(find / -name "eezyget-backend" -type d 2>/dev/null | head -1)
          echo "App directory: $APP_DIR"
          
          if [ -d "$APP_DIR/backend" ]; then
            echo "=== Entering backend directory ==="
            cd "$APP_DIR/backend"
            pwd
            ls -la
            
            echo "=== Git status ==="
            git status
            
            echo "=== Git pull ==="
            git pull origin main || echo "Git pull failed"
            
            echo "=== PM2 restart ==="
            pm2 restart all
            
            echo "=== Check server.js for CORS fix ==="
            grep -n "hardcoded" src/server.js || echo "CORS fix not found"
          else
            echo "Backend directory not found"
          fi