name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "=== VPS Investigation ==="
          pwd
          ls -la /
          
          echo "=== Finding git repo ==="
          find / -name ".git" -type d 2>/dev/null | head -5
          
          echo "=== Finding Node.js app ==="
          find / -name "package.json" 2>/dev/null | head -10
          find / -name "server.js" 2>/dev/null | head -10
          
          echo "=== PM2 status ==="
          pm2 status
          
          echo "=== PM2 logs ==="
          pm2 logs --lines 5